### ISSUE TITLE
XBox360 gamepad mapping, but not working over stream

### ISSUE THREAD

**Issue by flimshaw** [irtimmer/limelight-embedded#48]
I successfully created a map file using /dev/input/event2, and defined the mapping file in the launch command:

sudo java -jar limelight.jar stream -mapping event2.map x.x.x.x

I've tried declaring the input as /dev/input/js0 and event2 and both, but there is no effect when trying to use this in the steam stream window that opens, and there are no gamepads found when inspecting the settings in steam.

The console is outputting some debug info in the background, some video data and then an integer that seems to correspond to the buttons I'm pressing on the gamepad, so data is getting as far as that, but not being passed onto steam on the remote computer.

**Comment by aPollO2k** [comment]
I have the same issue. Analog sticks works fine for me but a button press will not reconized by steam. In xboxdrv messages it will be displayed. The output of xboxdrv shows that all buttons are working and reconized by the Kernel driver  but moonlight/steam does not. I can only switch between the games in the list but not start a game with controller.

**Comment by pdawg17** [comment]
Same issue...
