### ISSUE TITLE
Error Code 522

### ISSUE THREAD

**Issue by themalleges** [irtimmer/limelight-embedded#61]
Hey Guys
I have a big Problem with limelight-pi. Pairing works fine but when i try to connect to the pc i get
an error 522 game management problem ! 
I also tried limelight emmbed 1.1.1 on the Raspberry Pi but there was only Sound and I could input to the Game but no Video Output (Wrong Codec) !
I am not enough familliar to java code to connect the to Problems (get Video codec from Limelight-pi in the limelight 1.1.1 jar )
I hope someone reads this because i'd like to get it work ;)

**Comment by irtimmer** [comment]
Game management is GFE bug
