### ISSUE TITLE
Getting errors: "Java Broken Pipe" and "CreatePanoramaUIEngine Failed for Big Picture"

### ISSUE THREAD

**Issue by GhostWriterPi** [irtimmer/limelight-embedded#63]
I am new to this, so bear with me. 

- Using Rasbian (Watchdog is enabled and resolution has been configured http://www.webtechgadgetry.com/2013/12/make-raspberry-pi-use-full-resolution-monitor/)
- Installed oracle-java8-jdk
- installed libopus0
- Downloaded limelight.jar
- Using Steam Beta
- Using Nvidia 344.75
- Steam and GeForce Experience are both open on the desktop
- Host is using a static IP
- Paired devices successfully 
- When I enter "java -jar limelight.jar stream 192.168.x.xxx" Big Picture luanches, but only on my PC, nothing displays on the Pi, and I get this error: http://i.imgur.com/LB5Fd8M.png
- When I try again I get this error: http://i.imgur.com/H06LBFg.png

What is going on here? Am I using the wrong command?

**Comment by irtimmer** [comment]
Is a bug in Steam not in Limelight.
