### ISSUE TITLE
Video stutter every 20seconds or so

### ISSUE THREAD

**Issue by scoobyd00** [irtimmer/limelight-embedded#79]
Ive been using limelight on my PI and have had good performance, since updating to the latest release ive started to get video issues whereby every 20 seconds or so the graphics go from being butterly smooth to lagging, the lagging lasts for about 3 seconds or so and then it becomes butterly smooth again.

Any ideas?

**Comment by scoobyd00** [comment]
Tried lowering bitrate to see if that makes any difference but it doesnt.
For information i have a xbox wireless receiver connected to my pc and ive disabled the relevant files in the nvida folders.
When the video stuttering occurs the sound is still fine and doesnt stutter.

**Comment by Haris1977** [comment]
Same problem but not every 20 sec. I would say it happens in a random way for me. I think it must be looked.

Have opened a relevant issue - and other ones - here 

https://github.com/irtimmer/moonlight-embedded/issues/252

**Comment by peterden** [comment]
I have the same issue, using a samsung galaxy note 3, over a 5ghz wifi network. It stutters randomly, not exactly every 20 seconds, but stutters about 3 seconds, the audio isn't stuttering at all when the video does.
