### ISSUE TITLE
Audio output on host PC instead of Raspberry

### ISSUE THREAD

**Issue by Navok85** [irtimmer/limelight-embedded#97]
Tested on an fresh raspbian installation with GFE 2.2.2.0 and limelight embedded 1.2.1

Video works, but sound is coming on the host pc insted of the raspberry.

**Comment by Navok85** [comment]
Sorry for opening this issue. 

Problem was the GFE 2.2.2.0 HDMI audio driver, which wasn't installed correctly.

**Comment by havnar** [comment]
is there a way for me to have audio on both devices? (I.E. can I be gaming in my room so somebody else can watch me in another room) I could't see any of configuring that anywhere.

**Comment by irtimmer** [comment]
Please don't use random issue's for your own questions.
